version: '1.0'
name: branch-pipeline
displayName: BranchPipeline
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '21'
        mavenVersion: 3.6.3
        commands:
          - mvn -B clean package -Dmaven.test.skip=true
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./target
        strategy: {}
  - name: test
    displayName: 测试
    strategy: naturally
    trigger: auto
    steps:
      - step: ut@maven
        name: unit_test_maven
        displayName: Maven 单元测试
        jdkVersion: '21'
        mavenVersion: 3.6.3
        commands:
          - '# Maven单元测试默认命令'
          - mvn -B test -Dmaven.test.failure.ignore=true
          - mvn surefire-report:report-only
          - mvn site -DgenerateReports=false
        report:
          path: ./target/site
          index: surefire-report.html
        checkpoints: []
        settings: []
        caches:
          - ~/.m2
        notify: []
        strategy:
          retry: '0'
