ALTER TABLE team ADD COLUMN is_deleted TINYINT(1) DEFAULT 0;
ALTER TABLE news ADD COLUMN is_deleted TINYINT(1) DEFAULT 0;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE team;
TRUNCATE TABLE news;
SET FOREIGN_KEY_CHECKS = 1;